{% set name = "dbbot-sqlalchemy" %}
{% set version = "0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/dbbot-sqlalchemy-{{ version }}.tar.gz
  sha256: b8a0f6584311e1f89f83e79d3054f67e45974dcb26e30a36daf54c8b423e7b4b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - robotframework
    - sqlalchemy

test:
  imports:
    - dbbot
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/pbylicki/DbBot-SQLAlchemy
  summary: A tool for inserting Robot Framework test run results into SQL database using SQLAlchemy.
  license: Apache-2.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - marcodomingues99
